[project]
name = "pc-monitoring-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shurik", email = "sanya.kucheryavvkh@bk.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.31.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "mypy>=2.4.0",
    "psutil>=7.2.2",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.4",
    "ruff>=0.16.10",
]

[project.scripts]
pc-monitoring-bot = "bot.run:main"

[tool.uv.build-backend]
module-root = 'app'
module-name = 'bot'

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort (сортировка импортов)
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "RUF",  # ruff-specific
]
ignore = [
    "E501",
    "RUF001"# line too long (line-length уже задан)
]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = ["psutil.*", "httpx.*"]
ignore_missing_imports = true
